import React,{useCallback,useState} from 'react';
import {View,Text,StyleSheet,FlatList,TouchableOpacity} from 'react-native';
import {useFocusEffect,useNavigation} from '@react-navigation/native';
import {useAuth} from '../../context/AuthContext';
import {useLocale} from '../../context/LocaleContext';
import {fetchStudentSchedules,Schedule} from '../../services/scheduleService';
const G='#0F9D58',I='#1C1C1E',S='#8A9099';
export default function StudentScheduleScreen(){const nav=useNavigation();const{token}=useAuth();const{t}=useLocale();const[data,setData]=useState<Schedule[]>([]);const[loading,setLoading]=useState(true);const load=useCallback(async()=>{if(!token)return;setLoading(true);try{setData(await fetchStudentSchedules(token))}finally{setLoading(false)}},[token]);useFocusEffect(useCallback(()=>{load()},[load]));return <View style={st.root}><View style={st.header}><TouchableOpacity onPress={()=>nav.goBack()}><Text style={st.back}>‹</Text></TouchableOpacity><Text style={st.title}>{t('student_schedule.title','My Schedule')}</Text></View><FlatList data={data} refreshing={loading} onRefresh={load} keyExtractor={(x)=>String(x.id)} contentContainerStyle={st.list} ListEmptyComponent={<Text style={st.empty}>{t('student_schedule.empty','No published schedule yet.')}</Text>} renderItem={({item})=><View style={st.card}><Text style={st.day}>{item.day}</Text><Text style={st.time}>{String(item.starting_hour).padStart(2,'0')}:{String(item.starting_minute).padStart(2,'0')} - {String(item.ending_hour).padStart(2,'0')}:{String(item.ending_minute).padStart(2,'0')}</Text><Text style={st.meta}>{t('student_schedule.subject_label','Subject')} {item.subject_id} · {t('student_schedule.teacher_label','Teacher')} {item.teacher_id}</Text>{item.room_name?<Text style={st.meta}>{t('student_schedule.room_label','Room')}: {item.room_name}</Text>:null}</View>}/></View>}
const st=StyleSheet.create({root:{flex:1,backgroundColor:'#F6F7F9'},header:{flexDirection:'row',alignItems:'center',padding:16},back:{fontSize:32,color:G},title:{fontSize:18,fontWeight:'700',color:I,marginLeft:10},list:{padding:16},card:{backgroundColor:'#fff',borderRadius:16,padding:16,marginBottom:10},day:{fontWeight:'800',color:G},time:{fontSize:20,fontWeight:'800',color:I,marginTop:4},meta:{fontSize:12,color:S,marginTop:5},empty:{textAlign:'center',color:S,marginTop:36}});
