import React, { useCallback, useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import { useFocusEffect, useNavigation } from '@react-navigation/native';
import { useAuth } from '../../context/AuthContext';
import { useLocale } from '../../context/LocaleContext';
import { fetchStudentProgress, ProgressSummary } from '../../services/studentProgressService';
const GREEN='#0F9D58', INK='#1C1C1E', SUBTLE='#8A9099';
export default function StudentProgressScreen(){ const navigation=useNavigation(); const {token}=useAuth(); const {t}=useLocale(); const [data,setData]=useState<ProgressSummary|null>(null); const [error,setError]=useState<string|null>(null); const load=useCallback(async()=>{if(!token)return;try{setData(await fetchStudentProgress(token));}catch(e:any){setError(e?.message??t('student_progress.load_error','Could not load progress.'));}},[token,t]); useFocusEffect(useCallback(()=>{load();},[load])); return <View style={styles.root}><View style={styles.header}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={styles.back}>‹</Text></TouchableOpacity><Text style={styles.title}>{t('student_progress.title','My Progress')}</Text></View><ScrollView contentContainerStyle={styles.content}>{error&&<Text style={styles.error}>{error}</Text>}<View style={styles.hero}><Text style={styles.heroLabel}>{t('student_progress.attendance_rate','Attendance rate')}</Text><Text style={styles.heroValue}>{data?.attendance_rate==null?'-':`${data.attendance_rate}%`}</Text><Text style={styles.heroSub}>{data?.attendance_total??0} {t('student_progress.attendance_entries','recorded attendance entries')}</Text></View><View style={styles.card}><Text style={styles.cardTitle}>{t('student_progress.attendance_breakdown','Attendance breakdown')}</Text><View style={styles.grid}><Metric label={t('student_progress.present','Present')} value={data?.present??0}/><Metric label={t('student_progress.late','Late')} value={data?.late??0}/><Metric label={t('student_progress.excused','Excused')} value={data?.excused??0}/><Metric label={t('student_progress.absent','Absent')} value={data?.absent??0}/></View></View><View style={styles.card}><Text style={styles.cardTitle}>{t('student_progress.subject_averages','Subject averages')}</Text>{data?.grades_available&&data.subject_averages.length?data.subject_averages.map(x=><View key={x.subject_id} style={styles.subject}><Text style={styles.subjectName}>{x.subject_name}</Text><Text style={styles.subjectScore}>{x.average}%</Text></View>):<Text style={styles.note}>{data?.grades_note??t('student_progress.no_averages','No released subject averages yet.')}</Text>}</View></ScrollView></View> }
function Metric({label,value}:{label:string,value:number}){return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:'#F6F7F9'},header:{flexDirection:'row',alignItems:'center',padding:16},back:{fontSize:32,color:GREEN,lineHeight:30},title:{fontSize:18,fontWeight:'700',color:INK,marginLeft:10},content:{padding:16,paddingBottom:40},hero:{backgroundColor:'#123F2E',borderRadius:22,padding:22,marginBottom:14},heroLabel:{color:'#B9E9CC',fontSize:13},heroValue:{color:'#fff',fontSize:40,fontWeight:'800',marginTop:4},heroSub:{color:'#D8F2E1',fontSize:12,marginTop:4},card:{backgroundColor:'#fff',borderRadius:18,padding:18,marginBottom:14},cardTitle:{fontSize:16,fontWeight:'700',color:INK,marginBottom:16},grid:{flexDirection:'row',flexWrap:'wrap'},metric:{width:'50%',marginBottom:16},metricValue:{fontSize:24,fontWeight:'800',color:GREEN},metricLabel:{fontSize:12,color:SUBTLE,marginTop:2},subject:{flexDirection:'row',justifyContent:'space-between',paddingVertical:11,borderBottomWidth:1,borderBottomColor:'#EEF0F2'},subjectName:{color:INK},subjectScore:{fontWeight:'800',color:GREEN},note:{fontSize:13,color:SUBTLE,lineHeight:19},error:{color:'#B3261E',marginBottom:12}});
