import React, { useCallback, useState } from 'react';
import { View, Text, StyleSheet, FlatList, TouchableOpacity } from 'react-native';
import { useFocusEffect, useNavigation } from '@react-navigation/native';
import { useAuth } from '../../context/AuthContext';
import { useLocale } from '../../context/LocaleContext';
import { fetchStudentAttendance, AttendanceItem, AttendanceSummary } from '../../services/studentProgressService';
import { Skeleton } from '../../components/Skeleton';

const GREEN = '#0F9D58'; const SOFT = '#E7F5EC'; const INK = '#1C1C1E'; const SUBTLE = '#8A9099';
function Stat({ label, value }: { label: string; value: string | number }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
export default function StudentAttendanceScreen() {
  const navigation = useNavigation(); const { token } = useAuth(); const { t } = useLocale(); const now = new Date();
  const labels: Record<string,string> = { present: t('student_attendance.present', 'Present'), late: t('student_attendance.late', 'Late'), excused: t('student_attendance.excused', 'Excused'), absent: t('student_attendance.absent', 'Absent') };
  const [month, setMonth] = useState(now.getMonth()+1); const [year] = useState(now.getFullYear());
  const [items, setItems] = useState<AttendanceItem[]>([]); const [summary, setSummary] = useState<AttendanceSummary | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { if (!token) return; setLoading(true); setError(null); try { const data = await fetchStudentAttendance(token, month, year); setItems(data.items); setSummary(data.summary); } catch (e:any) { setError(e?.message ?? t('student_attendance.load_error', 'Could not load attendance.')); } finally { setLoading(false); } }, [token, month, year, t]);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const shift = (delta:number) => { let next=month+delta; if(next<1||next>12)return; setMonth(next); };
  return <View style={styles.root}><View style={styles.header}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>‹</Text></TouchableOpacity><Text style={styles.title}>{t('student_attendance.title', 'Attendance')}</Text></View><View style={styles.month}><TouchableOpacity onPress={()=>shift(-1)}><Text style={styles.arrow}>‹</Text></TouchableOpacity><Text style={styles.monthText}>{new Date(year, month-1, 1).toLocaleString('en-US',{month:'long'})} {year}</Text><TouchableOpacity onPress={()=>shift(1)}><Text style={styles.arrow}>›</Text></TouchableOpacity></View>{summary && <View style={styles.card}><View style={styles.stats}><Stat label={t('student_attendance.rate', 'Rate')} value={summary.rate == null ? '-' : `${summary.rate}%`} /><Stat label={t('student_attendance.present', 'Present')} value={summary.present}/><Stat label={t('student_attendance.late', 'Late')} value={summary.late}/><Stat label={t('student_attendance.absent', 'Absent')} value={summary.absent}/></View></View>}{error && <Text style={styles.error}>{error}</Text>}{loading ? <Skeleton /> : <FlatList data={items} keyExtractor={x=>String(x.id)} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={styles.empty}>{t('student_attendance.empty', 'No attendance records for this month.')}</Text>} renderItem={({item})=><View style={styles.row}><View><Text style={styles.date}>{item.date}</Text><Text style={styles.sub}>{item.is_homeroom ? t('student_attendance.homeroom', 'Homeroom') : t('student_attendance.subject_attendance', 'Subject attendance')}</Text></View><Text style={[styles.status, item.status==='absent'&&styles.absent]}>{labels[item.status] ?? item.status}</Text></View>} />}</View>;
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:'#F6F7F9'},header:{flexDirection:'row',alignItems:'center',padding:16},back:{fontSize:32,color:GREEN,lineHeight:30},title:{fontSize:18,fontWeight:'700',color:INK,marginLeft:10},month:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:20,paddingBottom:12},monthText:{fontWeight:'700',color:INK},arrow:{fontSize:28,color:GREEN},card:{margin:16,marginTop:4,padding:16,borderRadius:18,backgroundColor:'#fff'},stats:{flexDirection:'row',justifyContent:'space-between'},stat:{alignItems:'center',flex:1},statValue:{fontSize:20,fontWeight:'800',color:INK},statLabel:{fontSize:11,color:SUBTLE,marginTop:4},list:{padding:16,paddingTop:0},row:{backgroundColor:'#fff',borderRadius:14,padding:14,marginBottom:10,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},date:{fontWeight:'700',color:INK},sub:{fontSize:11,color:SUBTLE,marginTop:4},status:{color:GREEN,fontWeight:'700',backgroundColor:SOFT,paddingHorizontal:10,paddingVertical:6,borderRadius:12},absent:{color:'#B3261E',backgroundColor:'#FDECEC'},error:{marginHorizontal:16,color:'#B3261E'},empty:{textAlign:'center',color:SUBTLE,marginTop:36}});
